# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2025 ETH Zurich.

name: verify

on:
  push: # run this workflow on every push
  pull_request: # run this workflow on every pull_request
  workflow_dispatch: # allow to manually trigger this workflow

jobs:
  verify-packages:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ghcr.io/viperproject/gobra:v26.02
    env:
      MOD_NAME: github.com/felixlinker/keytrans-verification
      EXCLUDE_PKGS: "main"
      UNARY_MODE_PKGS: "proofs utils trees"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create stats dir
        run: mkdir .gobra-unary .gobra-hyper

      - name: Verify packages (without hyperMode)
        run: |
          java -jar -Xss128m /gobra/gobra.jar \
            --gobraDirectory .gobra-unary \
            --module ${{ env.MOD_NAME }} \
            --hyperMode off \
            --recursive \
            --include "." ".verification" \
            --includePackages ${{ env.UNARY_MODE_PKGS }}

      - name: Upload Gobra statistics
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: unary-stats.json
          path: .gobra-unary/stats.json

      - name: Verify packages (with hyperMode)
        run: |
          java -jar -Xss128m /gobra/gobra.jar \
            --gobraDirectory .gobra-hyper \
            --module ${{ env.MOD_NAME }} \
            --hyperMode extended \
            --recursive \
            --include "." ".verification" \
            --excludePackages ${{ env.EXCLUDE_PKGS }} ${{ env.UNARY_MODE_PKGS }}

      - name: Upload Gobra statistics
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: hyper-stats.json
          path: .gobra-hyper/stats.json


  test-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Test all packages
        run: go test ./...
